services:
  db:
    image: postgres:16-alpine
    container_name: coursetracker-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-coursetracker}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
  db-push:
    build:
      context: ./
      dockerfile: Dockerfile
      target: db-push
    container_name: coursetracker-db-push
    restart: "no"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-coursetracker}
    depends_on:
      db:
        condition: service_healthy
  gateway:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: coursetracker-gateway
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-coursetracker}
    depends_on:
      db:
        condition: service_healthy
      db-push:
        condition: service_completed_successfully

volumes:
  pgdata:
