import { sql } from "drizzle-orm";

import { db } from "@/db/index";

type ExistsRow = { exists: boolean } & Record<string, unknown>;
type ConstraintRow = { constraint_name: string } & Record<string, unknown>;

// Idempotent runtime migration that consolidates the Domain + Radar features:
//   - moves `radar_quadrants` / `radar_rings` rows into a JSONB column on
//     `domains` (`radar_config`)
//   - drops `has_radar` (every domain now has a radar; emptiness is derived
//     from radar_config)
//   - makes `radar_blips.quadrant_id` and `radar_blips.ring_id` nullable so a
//     blip can represent "topic in domain, not yet placed on the radar"
//   - drops the `topics_to_domains` junction; backfills its rows as blips
//     with NULL quadrant/ring
//   - drops the now-empty `radar_quadrants` and `radar_rings` tables
export async function migrateConsolidateRadar() {
  // Always ensure radar_config exists — drizzle-kit push in a non-TTY
  // container can drop has_radar without adding radar_config, leaving the DB
  // in a state where the has_radar guard below would skip the column add.
  await db.execute(sql`
    ALTER TABLE domains
    ADD COLUMN IF NOT EXISTS radar_config JSONB NOT NULL
    DEFAULT '{"quadrants":[],"rings":[]}'::jsonb
  `);

  const hasRadarColumn = await db.execute<ExistsRow>(sql`
    SELECT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_name = 'domains' AND column_name = 'has_radar'
    ) AS exists
  `);
  if (!hasRadarColumn.rows[0]?.exists) {
    return;
  }

  await db.transaction(async (tx) => {
    const quadrantsTableExists = await tx.execute<ExistsRow>(sql`
      SELECT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'radar_quadrants'
      ) AS exists
    `);
    const ringsTableExists = await tx.execute<ExistsRow>(sql`
      SELECT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'radar_rings'
      ) AS exists
    `);

    if (quadrantsTableExists.rows[0]?.exists && ringsTableExists.rows[0]?.exists) {
      await tx.execute(sql`
        UPDATE domains d SET radar_config = jsonb_build_object(
          'quadrants', COALESCE((
            SELECT jsonb_agg(
              jsonb_build_object('id', q.id, 'name', q.name, 'position', q.position)
              ORDER BY q.position
            )
            FROM radar_quadrants q WHERE q.domain_id = d.id
          ), '[]'::jsonb),
          'rings', COALESCE((
            SELECT jsonb_agg(
              jsonb_build_object('id', r.id, 'name', r.name, 'position', r.position)
              ORDER BY r.position
            )
            FROM radar_rings r WHERE r.domain_id = d.id
          ), '[]'::jsonb)
        )
      `);
    }

    await tx.execute(sql`ALTER TABLE radar_blips ALTER COLUMN quadrant_id DROP NOT NULL`);
    await tx.execute(sql`ALTER TABLE radar_blips ALTER COLUMN ring_id DROP NOT NULL`);

    // FK constraint names are auto-generated by Drizzle; look them up rather
    // than hard-coding so this works against either old or current naming.
    const dropFkForColumn = async (column: "quadrant_id" | "ring_id") => {
      const result = await tx.execute<ConstraintRow>(sql`
        SELECT tc.constraint_name FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_name = kcu.constraint_name
         AND tc.table_schema = kcu.table_schema
        WHERE tc.table_name = 'radar_blips'
          AND tc.constraint_type = 'FOREIGN KEY'
          AND kcu.column_name = ${column}
      `);
      for (const row of result.rows) {
        await tx.execute(
          sql`ALTER TABLE radar_blips DROP CONSTRAINT IF EXISTS ${sql.identifier(row.constraint_name)}`,
        );
      }
    };
    await dropFkForColumn("quadrant_id");
    await dropFkForColumn("ring_id");

    const ttdExists = await tx.execute<ExistsRow>(sql`
      SELECT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'topics_to_domains'
      ) AS exists
    `);
    if (ttdExists.rows[0]?.exists) {
      await tx.execute(sql`
        INSERT INTO radar_blips (id, domain_id, topic_id, quadrant_id, ring_id)
        SELECT gen_random_uuid()::text, ttd.domain_id, ttd.topic_id, NULL, NULL
        FROM topics_to_domains ttd
        WHERE NOT EXISTS (
          SELECT 1 FROM radar_blips b
          WHERE b.domain_id = ttd.domain_id AND b.topic_id = ttd.topic_id
        )
      `);
      await tx.execute(sql`DROP TABLE topics_to_domains`);
    }

    if (quadrantsTableExists.rows[0]?.exists) {
      await tx.execute(sql`DROP TABLE radar_quadrants`);
    }
    if (ringsTableExists.rows[0]?.exists) {
      await tx.execute(sql`DROP TABLE radar_rings`);
    }

    await tx.execute(sql`ALTER TABLE domains DROP COLUMN has_radar`);
  });
}
