/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailiesRouteImport } from './routes/dailies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as DomainsIndexRouteImport } from './routes/domains.index'
import { Route as DailiesIndexRouteImport } from './routes/dailies.index'
import { Route as TopicsIdRouteImport } from './routes/topics.$id'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as ResourcesIdRouteImport } from './routes/resources.$id'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as DomainsIdRouteImport } from './routes/domains.$id'
import { Route as DailiesIdRouteImport } from './routes/dailies.$id'
import { Route as TopicsIdIndexRouteImport } from './routes/topics.$id.index'
import { Route as TasksIdIndexRouteImport } from './routes/tasks.$id.index'
import { Route as ResourcesIdIndexRouteImport } from './routes/resources.$id.index'
import { Route as ProvidersIdIndexRouteImport } from './routes/providers.$id.index'
import { Route as DomainsIdIndexRouteImport } from './routes/domains.$id.index'
import { Route as DailiesIdIndexRouteImport } from './routes/dailies.$id.index'
import { Route as TopicsIdEditRouteImport } from './routes/topics.$id.edit'
import { Route as TasksIdEditRouteImport } from './routes/tasks.$id.edit'
import { Route as ResourcesIdEditRouteImport } from './routes/resources.$id.edit'
import { Route as ProvidersIdEditRouteImport } from './routes/providers.$id.edit'
import { Route as DomainsIdRadarRouteImport } from './routes/domains.$id.radar'
import { Route as DomainsIdEditRouteImport } from './routes/domains.$id.edit'
import { Route as DailiesIdEditRouteImport } from './routes/dailies.$id.edit'
import { Route as DomainsIdRadarIndexRouteImport } from './routes/domains.$id.radar.index'
import { Route as DomainsIdRadarEditRouteImport } from './routes/domains.$id.radar.edit'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailiesRoute = DailiesRouteImport.update({
  id: '/dailies',
  path: '/dailies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TopicsRoute,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersRoute,
} as any)
const DomainsIndexRoute = DomainsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DomainsRoute,
} as any)
const DailiesIndexRoute = DailiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DailiesRoute,
} as any)
const TopicsIdRoute = TopicsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TopicsRoute,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TasksRoute,
} as any)
const ResourcesIdRoute = ResourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResourcesRoute,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProvidersRoute,
} as any)
const DomainsIdRoute = DomainsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DomainsRoute,
} as any)
const DailiesIdRoute = DailiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DailiesRoute,
} as any)
const TopicsIdIndexRoute = TopicsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TopicsIdRoute,
} as any)
const TasksIdIndexRoute = TasksIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksIdRoute,
} as any)
const ResourcesIdIndexRoute = ResourcesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesIdRoute,
} as any)
const ProvidersIdIndexRoute = ProvidersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersIdRoute,
} as any)
const DomainsIdIndexRoute = DomainsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DomainsIdRoute,
} as any)
const DailiesIdIndexRoute = DailiesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DailiesIdRoute,
} as any)
const TopicsIdEditRoute = TopicsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TopicsIdRoute,
} as any)
const TasksIdEditRoute = TasksIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TasksIdRoute,
} as any)
const ResourcesIdEditRoute = ResourcesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ResourcesIdRoute,
} as any)
const ProvidersIdEditRoute = ProvidersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProvidersIdRoute,
} as any)
const DomainsIdRadarRoute = DomainsIdRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => DomainsIdRoute,
} as any)
const DomainsIdEditRoute = DomainsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DomainsIdRoute,
} as any)
const DailiesIdEditRoute = DailiesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DailiesIdRoute,
} as any)
const DomainsIdRadarIndexRoute = DomainsIdRadarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DomainsIdRadarRoute,
} as any)
const DomainsIdRadarEditRoute = DomainsIdRadarEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DomainsIdRadarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dailies': typeof DailiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/domains': typeof DomainsRouteWithChildren
  '/onboard': typeof OnboardRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/topics': typeof TopicsRouteWithChildren
  '/dailies/$id': typeof DailiesIdRouteWithChildren
  '/domains/$id': typeof DomainsIdRouteWithChildren
  '/providers/$id': typeof ProvidersIdRouteWithChildren
  '/resources/$id': typeof ResourcesIdRouteWithChildren
  '/tasks/$id': typeof TasksIdRouteWithChildren
  '/topics/$id': typeof TopicsIdRouteWithChildren
  '/dailies/': typeof DailiesIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/dailies/$id/edit': typeof DailiesIdEditRoute
  '/domains/$id/edit': typeof DomainsIdEditRoute
  '/domains/$id/radar': typeof DomainsIdRadarRouteWithChildren
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/resources/$id/edit': typeof ResourcesIdEditRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
  '/topics/$id/edit': typeof TopicsIdEditRoute
  '/dailies/$id/': typeof DailiesIdIndexRoute
  '/domains/$id/': typeof DomainsIdIndexRoute
  '/providers/$id/': typeof ProvidersIdIndexRoute
  '/resources/$id/': typeof ResourcesIdIndexRoute
  '/tasks/$id/': typeof TasksIdIndexRoute
  '/topics/$id/': typeof TopicsIdIndexRoute
  '/domains/$id/radar/edit': typeof DomainsIdRadarEditRoute
  '/domains/$id/radar/': typeof DomainsIdRadarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboard': typeof OnboardRoute
  '/settings': typeof SettingsRoute
  '/dailies': typeof DailiesIndexRoute
  '/domains': typeof DomainsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/dailies/$id/edit': typeof DailiesIdEditRoute
  '/domains/$id/edit': typeof DomainsIdEditRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/resources/$id/edit': typeof ResourcesIdEditRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
  '/topics/$id/edit': typeof TopicsIdEditRoute
  '/dailies/$id': typeof DailiesIdIndexRoute
  '/domains/$id': typeof DomainsIdIndexRoute
  '/providers/$id': typeof ProvidersIdIndexRoute
  '/resources/$id': typeof ResourcesIdIndexRoute
  '/tasks/$id': typeof TasksIdIndexRoute
  '/topics/$id': typeof TopicsIdIndexRoute
  '/domains/$id/radar/edit': typeof DomainsIdRadarEditRoute
  '/domains/$id/radar': typeof DomainsIdRadarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dailies': typeof DailiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/domains': typeof DomainsRouteWithChildren
  '/onboard': typeof OnboardRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/topics': typeof TopicsRouteWithChildren
  '/dailies/$id': typeof DailiesIdRouteWithChildren
  '/domains/$id': typeof DomainsIdRouteWithChildren
  '/providers/$id': typeof ProvidersIdRouteWithChildren
  '/resources/$id': typeof ResourcesIdRouteWithChildren
  '/tasks/$id': typeof TasksIdRouteWithChildren
  '/topics/$id': typeof TopicsIdRouteWithChildren
  '/dailies/': typeof DailiesIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/dailies/$id/edit': typeof DailiesIdEditRoute
  '/domains/$id/edit': typeof DomainsIdEditRoute
  '/domains/$id/radar': typeof DomainsIdRadarRouteWithChildren
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/resources/$id/edit': typeof ResourcesIdEditRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
  '/topics/$id/edit': typeof TopicsIdEditRoute
  '/dailies/$id/': typeof DailiesIdIndexRoute
  '/domains/$id/': typeof DomainsIdIndexRoute
  '/providers/$id/': typeof ProvidersIdIndexRoute
  '/resources/$id/': typeof ResourcesIdIndexRoute
  '/tasks/$id/': typeof TasksIdIndexRoute
  '/topics/$id/': typeof TopicsIdIndexRoute
  '/domains/$id/radar/edit': typeof DomainsIdRadarEditRoute
  '/domains/$id/radar/': typeof DomainsIdRadarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dailies'
    | '/dashboard'
    | '/domains'
    | '/onboard'
    | '/providers'
    | '/resources'
    | '/settings'
    | '/tasks'
    | '/topics'
    | '/dailies/$id'
    | '/domains/$id'
    | '/providers/$id'
    | '/resources/$id'
    | '/tasks/$id'
    | '/topics/$id'
    | '/dailies/'
    | '/domains/'
    | '/providers/'
    | '/resources/'
    | '/tasks/'
    | '/topics/'
    | '/dailies/$id/edit'
    | '/domains/$id/edit'
    | '/domains/$id/radar'
    | '/providers/$id/edit'
    | '/resources/$id/edit'
    | '/tasks/$id/edit'
    | '/topics/$id/edit'
    | '/dailies/$id/'
    | '/domains/$id/'
    | '/providers/$id/'
    | '/resources/$id/'
    | '/tasks/$id/'
    | '/topics/$id/'
    | '/domains/$id/radar/edit'
    | '/domains/$id/radar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboard'
    | '/settings'
    | '/dailies'
    | '/domains'
    | '/providers'
    | '/resources'
    | '/tasks'
    | '/topics'
    | '/dailies/$id/edit'
    | '/domains/$id/edit'
    | '/providers/$id/edit'
    | '/resources/$id/edit'
    | '/tasks/$id/edit'
    | '/topics/$id/edit'
    | '/dailies/$id'
    | '/domains/$id'
    | '/providers/$id'
    | '/resources/$id'
    | '/tasks/$id'
    | '/topics/$id'
    | '/domains/$id/radar/edit'
    | '/domains/$id/radar'
  id:
    | '__root__'
    | '/'
    | '/dailies'
    | '/dashboard'
    | '/domains'
    | '/onboard'
    | '/providers'
    | '/resources'
    | '/settings'
    | '/tasks'
    | '/topics'
    | '/dailies/$id'
    | '/domains/$id'
    | '/providers/$id'
    | '/resources/$id'
    | '/tasks/$id'
    | '/topics/$id'
    | '/dailies/'
    | '/domains/'
    | '/providers/'
    | '/resources/'
    | '/tasks/'
    | '/topics/'
    | '/dailies/$id/edit'
    | '/domains/$id/edit'
    | '/domains/$id/radar'
    | '/providers/$id/edit'
    | '/resources/$id/edit'
    | '/tasks/$id/edit'
    | '/topics/$id/edit'
    | '/dailies/$id/'
    | '/domains/$id/'
    | '/providers/$id/'
    | '/resources/$id/'
    | '/tasks/$id/'
    | '/topics/$id/'
    | '/domains/$id/radar/edit'
    | '/domains/$id/radar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailiesRoute: typeof DailiesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DomainsRoute: typeof DomainsRouteWithChildren
  OnboardRoute: typeof OnboardRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRouteWithChildren
  TopicsRoute: typeof TopicsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dailies': {
      id: '/dailies'
      path: '/dailies'
      fullPath: '/dailies'
      preLoaderRoute: typeof DailiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/providers/': {
      id: '/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/domains/': {
      id: '/domains/'
      path: '/'
      fullPath: '/domains/'
      preLoaderRoute: typeof DomainsIndexRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/dailies/': {
      id: '/dailies/'
      path: '/'
      fullPath: '/dailies/'
      preLoaderRoute: typeof DailiesIndexRouteImport
      parentRoute: typeof DailiesRoute
    }
    '/topics/$id': {
      id: '/topics/$id'
      path: '/$id'
      fullPath: '/topics/$id'
      preLoaderRoute: typeof TopicsIdRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/resources/$id': {
      id: '/resources/$id'
      path: '/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof ResourcesIdRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/domains/$id': {
      id: '/domains/$id'
      path: '/$id'
      fullPath: '/domains/$id'
      preLoaderRoute: typeof DomainsIdRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/dailies/$id': {
      id: '/dailies/$id'
      path: '/$id'
      fullPath: '/dailies/$id'
      preLoaderRoute: typeof DailiesIdRouteImport
      parentRoute: typeof DailiesRoute
    }
    '/topics/$id/': {
      id: '/topics/$id/'
      path: '/'
      fullPath: '/topics/$id/'
      preLoaderRoute: typeof TopicsIdIndexRouteImport
      parentRoute: typeof TopicsIdRoute
    }
    '/tasks/$id/': {
      id: '/tasks/$id/'
      path: '/'
      fullPath: '/tasks/$id/'
      preLoaderRoute: typeof TasksIdIndexRouteImport
      parentRoute: typeof TasksIdRoute
    }
    '/resources/$id/': {
      id: '/resources/$id/'
      path: '/'
      fullPath: '/resources/$id/'
      preLoaderRoute: typeof ResourcesIdIndexRouteImport
      parentRoute: typeof ResourcesIdRoute
    }
    '/providers/$id/': {
      id: '/providers/$id/'
      path: '/'
      fullPath: '/providers/$id/'
      preLoaderRoute: typeof ProvidersIdIndexRouteImport
      parentRoute: typeof ProvidersIdRoute
    }
    '/domains/$id/': {
      id: '/domains/$id/'
      path: '/'
      fullPath: '/domains/$id/'
      preLoaderRoute: typeof DomainsIdIndexRouteImport
      parentRoute: typeof DomainsIdRoute
    }
    '/dailies/$id/': {
      id: '/dailies/$id/'
      path: '/'
      fullPath: '/dailies/$id/'
      preLoaderRoute: typeof DailiesIdIndexRouteImport
      parentRoute: typeof DailiesIdRoute
    }
    '/topics/$id/edit': {
      id: '/topics/$id/edit'
      path: '/edit'
      fullPath: '/topics/$id/edit'
      preLoaderRoute: typeof TopicsIdEditRouteImport
      parentRoute: typeof TopicsIdRoute
    }
    '/tasks/$id/edit': {
      id: '/tasks/$id/edit'
      path: '/edit'
      fullPath: '/tasks/$id/edit'
      preLoaderRoute: typeof TasksIdEditRouteImport
      parentRoute: typeof TasksIdRoute
    }
    '/resources/$id/edit': {
      id: '/resources/$id/edit'
      path: '/edit'
      fullPath: '/resources/$id/edit'
      preLoaderRoute: typeof ResourcesIdEditRouteImport
      parentRoute: typeof ResourcesIdRoute
    }
    '/providers/$id/edit': {
      id: '/providers/$id/edit'
      path: '/edit'
      fullPath: '/providers/$id/edit'
      preLoaderRoute: typeof ProvidersIdEditRouteImport
      parentRoute: typeof ProvidersIdRoute
    }
    '/domains/$id/radar': {
      id: '/domains/$id/radar'
      path: '/radar'
      fullPath: '/domains/$id/radar'
      preLoaderRoute: typeof DomainsIdRadarRouteImport
      parentRoute: typeof DomainsIdRoute
    }
    '/domains/$id/edit': {
      id: '/domains/$id/edit'
      path: '/edit'
      fullPath: '/domains/$id/edit'
      preLoaderRoute: typeof DomainsIdEditRouteImport
      parentRoute: typeof DomainsIdRoute
    }
    '/dailies/$id/edit': {
      id: '/dailies/$id/edit'
      path: '/edit'
      fullPath: '/dailies/$id/edit'
      preLoaderRoute: typeof DailiesIdEditRouteImport
      parentRoute: typeof DailiesIdRoute
    }
    '/domains/$id/radar/': {
      id: '/domains/$id/radar/'
      path: '/'
      fullPath: '/domains/$id/radar/'
      preLoaderRoute: typeof DomainsIdRadarIndexRouteImport
      parentRoute: typeof DomainsIdRadarRoute
    }
    '/domains/$id/radar/edit': {
      id: '/domains/$id/radar/edit'
      path: '/edit'
      fullPath: '/domains/$id/radar/edit'
      preLoaderRoute: typeof DomainsIdRadarEditRouteImport
      parentRoute: typeof DomainsIdRadarRoute
    }
  }
}

interface DailiesIdRouteChildren {
  DailiesIdEditRoute: typeof DailiesIdEditRoute
  DailiesIdIndexRoute: typeof DailiesIdIndexRoute
}

const DailiesIdRouteChildren: DailiesIdRouteChildren = {
  DailiesIdEditRoute: DailiesIdEditRoute,
  DailiesIdIndexRoute: DailiesIdIndexRoute,
}

const DailiesIdRouteWithChildren = DailiesIdRoute._addFileChildren(
  DailiesIdRouteChildren,
)

interface DailiesRouteChildren {
  DailiesIdRoute: typeof DailiesIdRouteWithChildren
  DailiesIndexRoute: typeof DailiesIndexRoute
}

const DailiesRouteChildren: DailiesRouteChildren = {
  DailiesIdRoute: DailiesIdRouteWithChildren,
  DailiesIndexRoute: DailiesIndexRoute,
}

const DailiesRouteWithChildren =
  DailiesRoute._addFileChildren(DailiesRouteChildren)

interface DomainsIdRadarRouteChildren {
  DomainsIdRadarEditRoute: typeof DomainsIdRadarEditRoute
  DomainsIdRadarIndexRoute: typeof DomainsIdRadarIndexRoute
}

const DomainsIdRadarRouteChildren: DomainsIdRadarRouteChildren = {
  DomainsIdRadarEditRoute: DomainsIdRadarEditRoute,
  DomainsIdRadarIndexRoute: DomainsIdRadarIndexRoute,
}

const DomainsIdRadarRouteWithChildren = DomainsIdRadarRoute._addFileChildren(
  DomainsIdRadarRouteChildren,
)

interface DomainsIdRouteChildren {
  DomainsIdEditRoute: typeof DomainsIdEditRoute
  DomainsIdRadarRoute: typeof DomainsIdRadarRouteWithChildren
  DomainsIdIndexRoute: typeof DomainsIdIndexRoute
}

const DomainsIdRouteChildren: DomainsIdRouteChildren = {
  DomainsIdEditRoute: DomainsIdEditRoute,
  DomainsIdRadarRoute: DomainsIdRadarRouteWithChildren,
  DomainsIdIndexRoute: DomainsIdIndexRoute,
}

const DomainsIdRouteWithChildren = DomainsIdRoute._addFileChildren(
  DomainsIdRouteChildren,
)

interface DomainsRouteChildren {
  DomainsIdRoute: typeof DomainsIdRouteWithChildren
  DomainsIndexRoute: typeof DomainsIndexRoute
}

const DomainsRouteChildren: DomainsRouteChildren = {
  DomainsIdRoute: DomainsIdRouteWithChildren,
  DomainsIndexRoute: DomainsIndexRoute,
}

const DomainsRouteWithChildren =
  DomainsRoute._addFileChildren(DomainsRouteChildren)

interface ProvidersIdRouteChildren {
  ProvidersIdEditRoute: typeof ProvidersIdEditRoute
  ProvidersIdIndexRoute: typeof ProvidersIdIndexRoute
}

const ProvidersIdRouteChildren: ProvidersIdRouteChildren = {
  ProvidersIdEditRoute: ProvidersIdEditRoute,
  ProvidersIdIndexRoute: ProvidersIdIndexRoute,
}

const ProvidersIdRouteWithChildren = ProvidersIdRoute._addFileChildren(
  ProvidersIdRouteChildren,
)

interface ProvidersRouteChildren {
  ProvidersIdRoute: typeof ProvidersIdRouteWithChildren
  ProvidersIndexRoute: typeof ProvidersIndexRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersIdRoute: ProvidersIdRouteWithChildren,
  ProvidersIndexRoute: ProvidersIndexRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

interface ResourcesIdRouteChildren {
  ResourcesIdEditRoute: typeof ResourcesIdEditRoute
  ResourcesIdIndexRoute: typeof ResourcesIdIndexRoute
}

const ResourcesIdRouteChildren: ResourcesIdRouteChildren = {
  ResourcesIdEditRoute: ResourcesIdEditRoute,
  ResourcesIdIndexRoute: ResourcesIdIndexRoute,
}

const ResourcesIdRouteWithChildren = ResourcesIdRoute._addFileChildren(
  ResourcesIdRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesIdRoute: typeof ResourcesIdRouteWithChildren
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesIdRoute: ResourcesIdRouteWithChildren,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface TasksIdRouteChildren {
  TasksIdEditRoute: typeof TasksIdEditRoute
  TasksIdIndexRoute: typeof TasksIdIndexRoute
}

const TasksIdRouteChildren: TasksIdRouteChildren = {
  TasksIdEditRoute: TasksIdEditRoute,
  TasksIdIndexRoute: TasksIdIndexRoute,
}

const TasksIdRouteWithChildren =
  TasksIdRoute._addFileChildren(TasksIdRouteChildren)

interface TasksRouteChildren {
  TasksIdRoute: typeof TasksIdRouteWithChildren
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksIdRoute: TasksIdRouteWithChildren,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

interface TopicsIdRouteChildren {
  TopicsIdEditRoute: typeof TopicsIdEditRoute
  TopicsIdIndexRoute: typeof TopicsIdIndexRoute
}

const TopicsIdRouteChildren: TopicsIdRouteChildren = {
  TopicsIdEditRoute: TopicsIdEditRoute,
  TopicsIdIndexRoute: TopicsIdIndexRoute,
}

const TopicsIdRouteWithChildren = TopicsIdRoute._addFileChildren(
  TopicsIdRouteChildren,
)

interface TopicsRouteChildren {
  TopicsIdRoute: typeof TopicsIdRouteWithChildren
  TopicsIndexRoute: typeof TopicsIndexRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsIdRoute: TopicsIdRouteWithChildren,
  TopicsIndexRoute: TopicsIndexRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailiesRoute: DailiesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DomainsRoute: DomainsRouteWithChildren,
  OnboardRoute: OnboardRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
  ResourcesRoute: ResourcesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRouteWithChildren,
  TopicsRoute: TopicsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
