/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as DomainsIndexRouteImport } from './routes/domains.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as TopicsIdRouteImport } from './routes/topics.$id'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as DomainsIdRouteImport } from './routes/domains.$id'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as TopicsIdIndexRouteImport } from './routes/topics.$id.index'
import { Route as ProvidersIdIndexRouteImport } from './routes/providers.$id.index'
import { Route as DomainsIdIndexRouteImport } from './routes/domains.$id.index'
import { Route as CoursesIdIndexRouteImport } from './routes/courses.$id.index'
import { Route as TopicsIdEditRouteImport } from './routes/topics.$id.edit'
import { Route as ProvidersIdEditRouteImport } from './routes/providers.$id.edit'
import { Route as DomainsIdEditRouteImport } from './routes/domains.$id.edit'
import { Route as CoursesIdEditRouteImport } from './routes/courses.$id.edit'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TopicsRoute,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersRoute,
} as any)
const DomainsIndexRoute = DomainsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DomainsRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const TopicsIdRoute = TopicsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TopicsRoute,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProvidersRoute,
} as any)
const DomainsIdRoute = DomainsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DomainsRoute,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CoursesRoute,
} as any)
const TopicsIdIndexRoute = TopicsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TopicsIdRoute,
} as any)
const ProvidersIdIndexRoute = ProvidersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersIdRoute,
} as any)
const DomainsIdIndexRoute = DomainsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DomainsIdRoute,
} as any)
const CoursesIdIndexRoute = CoursesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesIdRoute,
} as any)
const TopicsIdEditRoute = TopicsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TopicsIdRoute,
} as any)
const ProvidersIdEditRoute = ProvidersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProvidersIdRoute,
} as any)
const DomainsIdEditRoute = DomainsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DomainsIdRoute,
} as any)
const CoursesIdEditRoute = CoursesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CoursesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/domains': typeof DomainsRouteWithChildren
  '/onboard': typeof OnboardRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/topics': typeof TopicsRouteWithChildren
  '/courses/$id': typeof CoursesIdRouteWithChildren
  '/domains/$id': typeof DomainsIdRouteWithChildren
  '/providers/$id': typeof ProvidersIdRouteWithChildren
  '/topics/$id': typeof TopicsIdRouteWithChildren
  '/courses/': typeof CoursesIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/courses/$id/edit': typeof CoursesIdEditRoute
  '/domains/$id/edit': typeof DomainsIdEditRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/topics/$id/edit': typeof TopicsIdEditRoute
  '/courses/$id/': typeof CoursesIdIndexRoute
  '/domains/$id/': typeof DomainsIdIndexRoute
  '/providers/$id/': typeof ProvidersIdIndexRoute
  '/topics/$id/': typeof TopicsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboard': typeof OnboardRoute
  '/courses': typeof CoursesIndexRoute
  '/domains': typeof DomainsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/courses/$id/edit': typeof CoursesIdEditRoute
  '/domains/$id/edit': typeof DomainsIdEditRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/topics/$id/edit': typeof TopicsIdEditRoute
  '/courses/$id': typeof CoursesIdIndexRoute
  '/domains/$id': typeof DomainsIdIndexRoute
  '/providers/$id': typeof ProvidersIdIndexRoute
  '/topics/$id': typeof TopicsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/domains': typeof DomainsRouteWithChildren
  '/onboard': typeof OnboardRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/topics': typeof TopicsRouteWithChildren
  '/courses/$id': typeof CoursesIdRouteWithChildren
  '/domains/$id': typeof DomainsIdRouteWithChildren
  '/providers/$id': typeof ProvidersIdRouteWithChildren
  '/topics/$id': typeof TopicsIdRouteWithChildren
  '/courses/': typeof CoursesIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/courses/$id/edit': typeof CoursesIdEditRoute
  '/domains/$id/edit': typeof DomainsIdEditRoute
  '/providers/$id/edit': typeof ProvidersIdEditRoute
  '/topics/$id/edit': typeof TopicsIdEditRoute
  '/courses/$id/': typeof CoursesIdIndexRoute
  '/domains/$id/': typeof DomainsIdIndexRoute
  '/providers/$id/': typeof ProvidersIdIndexRoute
  '/topics/$id/': typeof TopicsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/dashboard'
    | '/domains'
    | '/onboard'
    | '/providers'
    | '/topics'
    | '/courses/$id'
    | '/domains/$id'
    | '/providers/$id'
    | '/topics/$id'
    | '/courses/'
    | '/domains/'
    | '/providers/'
    | '/topics/'
    | '/courses/$id/edit'
    | '/domains/$id/edit'
    | '/providers/$id/edit'
    | '/topics/$id/edit'
    | '/courses/$id/'
    | '/domains/$id/'
    | '/providers/$id/'
    | '/topics/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboard'
    | '/courses'
    | '/domains'
    | '/providers'
    | '/topics'
    | '/courses/$id/edit'
    | '/domains/$id/edit'
    | '/providers/$id/edit'
    | '/topics/$id/edit'
    | '/courses/$id'
    | '/domains/$id'
    | '/providers/$id'
    | '/topics/$id'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/dashboard'
    | '/domains'
    | '/onboard'
    | '/providers'
    | '/topics'
    | '/courses/$id'
    | '/domains/$id'
    | '/providers/$id'
    | '/topics/$id'
    | '/courses/'
    | '/domains/'
    | '/providers/'
    | '/topics/'
    | '/courses/$id/edit'
    | '/domains/$id/edit'
    | '/providers/$id/edit'
    | '/topics/$id/edit'
    | '/courses/$id/'
    | '/domains/$id/'
    | '/providers/$id/'
    | '/topics/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DomainsRoute: typeof DomainsRouteWithChildren
  OnboardRoute: typeof OnboardRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
  TopicsRoute: typeof TopicsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/providers/': {
      id: '/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/domains/': {
      id: '/domains/'
      path: '/'
      fullPath: '/domains/'
      preLoaderRoute: typeof DomainsIndexRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/topics/$id': {
      id: '/topics/$id'
      path: '/$id'
      fullPath: '/topics/$id'
      preLoaderRoute: typeof TopicsIdRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/domains/$id': {
      id: '/domains/$id'
      path: '/$id'
      fullPath: '/domains/$id'
      preLoaderRoute: typeof DomainsIdRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/topics/$id/': {
      id: '/topics/$id/'
      path: '/'
      fullPath: '/topics/$id/'
      preLoaderRoute: typeof TopicsIdIndexRouteImport
      parentRoute: typeof TopicsIdRoute
    }
    '/providers/$id/': {
      id: '/providers/$id/'
      path: '/'
      fullPath: '/providers/$id/'
      preLoaderRoute: typeof ProvidersIdIndexRouteImport
      parentRoute: typeof ProvidersIdRoute
    }
    '/domains/$id/': {
      id: '/domains/$id/'
      path: '/'
      fullPath: '/domains/$id/'
      preLoaderRoute: typeof DomainsIdIndexRouteImport
      parentRoute: typeof DomainsIdRoute
    }
    '/courses/$id/': {
      id: '/courses/$id/'
      path: '/'
      fullPath: '/courses/$id/'
      preLoaderRoute: typeof CoursesIdIndexRouteImport
      parentRoute: typeof CoursesIdRoute
    }
    '/topics/$id/edit': {
      id: '/topics/$id/edit'
      path: '/edit'
      fullPath: '/topics/$id/edit'
      preLoaderRoute: typeof TopicsIdEditRouteImport
      parentRoute: typeof TopicsIdRoute
    }
    '/providers/$id/edit': {
      id: '/providers/$id/edit'
      path: '/edit'
      fullPath: '/providers/$id/edit'
      preLoaderRoute: typeof ProvidersIdEditRouteImport
      parentRoute: typeof ProvidersIdRoute
    }
    '/domains/$id/edit': {
      id: '/domains/$id/edit'
      path: '/edit'
      fullPath: '/domains/$id/edit'
      preLoaderRoute: typeof DomainsIdEditRouteImport
      parentRoute: typeof DomainsIdRoute
    }
    '/courses/$id/edit': {
      id: '/courses/$id/edit'
      path: '/edit'
      fullPath: '/courses/$id/edit'
      preLoaderRoute: typeof CoursesIdEditRouteImport
      parentRoute: typeof CoursesIdRoute
    }
  }
}

interface CoursesIdRouteChildren {
  CoursesIdEditRoute: typeof CoursesIdEditRoute
  CoursesIdIndexRoute: typeof CoursesIdIndexRoute
}

const CoursesIdRouteChildren: CoursesIdRouteChildren = {
  CoursesIdEditRoute: CoursesIdEditRoute,
  CoursesIdIndexRoute: CoursesIdIndexRoute,
}

const CoursesIdRouteWithChildren = CoursesIdRoute._addFileChildren(
  CoursesIdRouteChildren,
)

interface CoursesRouteChildren {
  CoursesIdRoute: typeof CoursesIdRouteWithChildren
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesIdRoute: CoursesIdRouteWithChildren,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface DomainsIdRouteChildren {
  DomainsIdEditRoute: typeof DomainsIdEditRoute
  DomainsIdIndexRoute: typeof DomainsIdIndexRoute
}

const DomainsIdRouteChildren: DomainsIdRouteChildren = {
  DomainsIdEditRoute: DomainsIdEditRoute,
  DomainsIdIndexRoute: DomainsIdIndexRoute,
}

const DomainsIdRouteWithChildren = DomainsIdRoute._addFileChildren(
  DomainsIdRouteChildren,
)

interface DomainsRouteChildren {
  DomainsIdRoute: typeof DomainsIdRouteWithChildren
  DomainsIndexRoute: typeof DomainsIndexRoute
}

const DomainsRouteChildren: DomainsRouteChildren = {
  DomainsIdRoute: DomainsIdRouteWithChildren,
  DomainsIndexRoute: DomainsIndexRoute,
}

const DomainsRouteWithChildren =
  DomainsRoute._addFileChildren(DomainsRouteChildren)

interface ProvidersIdRouteChildren {
  ProvidersIdEditRoute: typeof ProvidersIdEditRoute
  ProvidersIdIndexRoute: typeof ProvidersIdIndexRoute
}

const ProvidersIdRouteChildren: ProvidersIdRouteChildren = {
  ProvidersIdEditRoute: ProvidersIdEditRoute,
  ProvidersIdIndexRoute: ProvidersIdIndexRoute,
}

const ProvidersIdRouteWithChildren = ProvidersIdRoute._addFileChildren(
  ProvidersIdRouteChildren,
)

interface ProvidersRouteChildren {
  ProvidersIdRoute: typeof ProvidersIdRouteWithChildren
  ProvidersIndexRoute: typeof ProvidersIndexRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersIdRoute: ProvidersIdRouteWithChildren,
  ProvidersIndexRoute: ProvidersIndexRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

interface TopicsIdRouteChildren {
  TopicsIdEditRoute: typeof TopicsIdEditRoute
  TopicsIdIndexRoute: typeof TopicsIdIndexRoute
}

const TopicsIdRouteChildren: TopicsIdRouteChildren = {
  TopicsIdEditRoute: TopicsIdEditRoute,
  TopicsIdIndexRoute: TopicsIdIndexRoute,
}

const TopicsIdRouteWithChildren = TopicsIdRoute._addFileChildren(
  TopicsIdRouteChildren,
)

interface TopicsRouteChildren {
  TopicsIdRoute: typeof TopicsIdRouteWithChildren
  TopicsIndexRoute: typeof TopicsIndexRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsIdRoute: TopicsIdRouteWithChildren,
  TopicsIndexRoute: TopicsIndexRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DomainsRoute: DomainsRouteWithChildren,
  OnboardRoute: OnboardRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
  TopicsRoute: TopicsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
